---
title: "Untitled"
author: "Max Ranz de la Iglesia"
date: "2025-10-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("arules")
#install.packages("arulesViz")
#install.packages("tidyverse")
library(arules)
library(arulesViz)
library(FactoMineR)
library(tidyverse)
library(dplyr)
```
```{r}
bank_data<-read.csv("datos_missing.csv", header = TRUE, stringsAsFactors = TRUE)

# Quitamos las observaciones con Exited=NA y las variables de identificación

bank_data <- bank_data %>%
  filter(!is.na(Exited)) %>%
  select(-ID)

# Convertir numericas a categoricas

bank_data$Tenure <- cut(bank_data$Tenure, breaks=c(-1,3,7,10), labels=c("Corto","Medio","Largo"))
bank_data$NetPromoterScore <- cut(bank_data$NetPromoterScore, breaks=c(-1,3,7,10),labels=c("Insatisfecho","Satisfecho","Contento"))
bank_data$TransactionFrequency <- cut(bank_data$TransactionFrequency, breaks=c(0,25,35,58), labels=c("Baja","Media","Alta"))
bank_data$Age <- cut(bank_data$Age, breaks=c(0,30,45,92), labels=c("Joven","Adulto","Mayor"))
bank_data$ComplaintsCount <- ifelse(bank_data$ComplaintsCount>0, "ConReclamos", "SinReclamos")
bank_data$ComplaintsCount<-factor(bank_data$ComplaintsCount)
bank_data$EstimatedSalary <- cut(bank_data$EstimatedSalary, breaks=c(0,50000,100000,150000,199992.48),labels=c("Bajo","MedioBajo","MedioAlto","Alto"))
bank_data$AvgTransactionAmount <- cut(bank_data$AvgTransactionAmount, breaks=c(0,150,611.35), labels=c("Baja","Alta"))
bank_data$DigitalEngagementScore<- cut(bank_data$DigitalEngagementScore, breaks=c(0,50,75,100), labels=c("Bajo","Medio","Alto"))
bank_data$CreditScore <- cut(bank_data$CreditScore, breaks=c(0,600,750,850), labels=c("Bajo","Medio","Alto"))
bank_data$Balance <- cut(bank_data$Balance, breaks=c(-1,1,150000,250898.09),labels=c("Sin Saldo","Medio","Alto"))
bank_data$NumOfProducts<- cut(bank_data$NumOfProducts, breaks=c(0,2,4),right=FALSE,labels=c("Un Producto","Más de uno"))

# Convertimos las logicas

bank_data <- bank_data %>%
  mutate(
    HasCrCard = factor(HasCrCard, levels = c(0, 1), labels = c("No", "Sí")),
    SavingsAccountFlag = factor(SavingsAccountFlag, levels = c(0, 1), labels = c("No", "Sí")),
    IsActiveMember = factor(IsActiveMember, levels = c(0, 1), labels = c("No", "Sí")),
    Exited = factor(Exited, levels = c(0, 1), labels = c("No", "Sí"))
  )

```

```{r}
str(bank_data)
summary(bank_data)
```


```{r}
# ASSOCIATION RULES 

# CONVERTIR TODAS LAS VARIABLES A FACTORES 
# (las reglas de asociación solo funcionan con variables categóricas)

# CONVERTIR EN OBJETO DE TRANSACCIONES 
ttr_bank <- as(bank_data, "transactions")
ttr_bank
summary(ttr_bank)

# ANALIZAR EL NÚMERO DE ITEMS POR TRANSACCIÓN
inspect(ttr_bank[1:6])
SIZE <- size(ttr_bank)
summary(SIZE)
data.frame(SIZE) %>%
  ggplot(aes(x = SIZE)) +
  geom_histogram(fill = "skyblue", color = "black") +
  labs(title = "Distribución del tamaño de las transacciones", x = "Número de items", y = "Frecuencia") +
  theme_bw()

# FRECUENCIA DE ITEMS 
itemFrequencyPlot(ttr_bank, topN = 20, type = "absolute", cex.names = 0.7)

# APLICAR APRIORI 
# Ajusta los parámetros según la densidad de tu dataset:
rules_bank <- apriori(
  ttr_bank,
  parameter = list(supp = 0.01, conf = 0.6, minlen = 1, maxlen = 5)
)

summary(rules_bank)
inspect(head(rules_bank, 10))

# ORDENAR REGLAS 
rules_lift <- sort(rules_bank, by = "lift", decreasing = TRUE)
inspect(head(rules_lift, 10))
rules_conf <- sort(rules_bank, by = "confidence", decreasing = TRUE)
inspect(head(rules_conf, 10))

# FILTRAR REGLAS ESPECÍFICAS 
# Ejemplo: clientes que abandonaron el banco (Exited=1)
rules_exited <- subset(rules_bank, subset = rhs %in% "Exited=Sí")
inspect(sort(rules_exited, by = "lift")[1:10])

rules_exitedNO <- subset(rules_bank, subset = rhs %in% "Exited=No")
inspect(sort(rules_exited, by = "lift")[1:10])

rules_exited_izquierda <- subset(rules_bank, subset = lhs %in% "Exited=Sí")
inspect(sort(rules_exited, by = "lift")[1:10])

# ELIMINAR REGLAS REDUNDANTES
reglas_redundantes <- rules_bank[is.redundant(x = rules_bank, measure = "confidence")]
reglas_redundantes

reglas_Noredund <- rules_bank[!is.redundant(x = rules_bank, measure = "confidence")]
reglas_Noredund

reglas_Noredund <- sort(reglas_Noredund,by="lift")
inspect(reglas_Noredund[1:10])


```





