---
title: "Untitled"
author: "Max Ranz de la Iglesia"
date: "2025-10-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Análisis Descriptivo de los datos

## Lectura de los datos

```{r}
#install.packages("dplyr")
library(dplyr)
```

```{r}
train <- read.csv("train.csv", header = TRUE, sep = ",")
test  <- read.csv("test.csv", header = TRUE, sep = ",")
datos <- bind_rows(train, test)

dim(datos)       
head(datos)       
summary(datos)   
```

## Tipos de variables
```{r}
clases <- sapply(datos, class)
datos$HasCrCard <- factor(datos$HasCrCard)
datos$IsActiveMember <- factor(datos$IsActiveMember)
datos$SavingsAccountFlag <- factor(datos$SavingsAccountFlag)

varNum <- names(clases)[which(clases %in% c("numeric", "integer"))]
varCat <- names(clases)[which(clases %in% c("character", "factor"))]
```
## Análisis exploratorio Univariante

### Numéricas

```{r}
library(psych)
psych::describe(datos[, varNum])
```
```{r}
par(mfrow = c(2, 4))  
for (var in varNum) {
  hist(datos[, var], main = paste0("Histograma variable ", var))
  boxplot(datos[, var], main = paste0("Boxplot variable ", var))
}

```


### Categóricas
```{r}
for (var in varCat) {
  tablaAbs <- data.frame(table(datos[, var]))
  tablaFreq <- data.frame(table(datos[, var])/sum(table(datos[, var])))
  m <- match(tablaAbs$Var1, tablaFreq$Var1)
  tablaAbs[, "FreqRel"] <- tablaFreq[m, "Freq"]
  colnames(tablaAbs) <- c("Categoria", "FreqAbs", "FreqRel")
  
  cat("===============", var, "===================================\n")
  print(tablaAbs)
  cat("==================================================\n")
}
```
```{r}
par(mfrow = c(2, 3))  
for (var in varCat) {
  barplot(table(datos[, var]))
}
par(mfrow = c(1, 1))  
```
```{r}
library(ggplot2)
library(gridExtra)

plots <- list()  # lista vacía
i <- 1           # índice

for (var in varCat) {
  tabla <- data.frame(table(datos[, var]) / sum(table(datos[, var])))
  
  p <- ggplot(data = tabla, aes(x = Var1, y = Freq)) +
        geom_bar(stat = "identity", fill = "steelblue") +
        geom_text(aes(label = paste0(round(Freq * 100, 2), "%")),
                  vjust = 0.9, color = "white", size = 3.5) +
        theme_minimal() +
        labs(title = paste("Distribución de", var), x = var, y = "Proporción")
  
  plots[[i]] <- p
  i <- i + 1
}

# Mostrar todos los gráficos en un grid (ejemplo con 2 columnas)
grid.arrange(grobs = plots, ncol = 2)
```
## Análisis exploratorio Bivariante

### Num vs Num
```{r}
cor(datos[, varNum])
```
```{r}
library(PerformanceAnalytics)
chart.Correlation(as.matrix(datos[, varNum]),histogram = TRUE,pch=12)
```

### Num vs Cat
```{r}
for (varN in varNum) {
  for (varC in varCat) {
   print(psych::describeBy(datos[, varN], group = datos[, varC])) 
  }
}
```

```{r}
library(ggplot2)
library(gridExtra)

plots <- list()
i <- 1

for (varC in varCat) {
  for (varN in varNum) {
    
    grafico <- ggplot(datos, aes(x = .data[[varN]], fill = .data[[varC]])) + 
      geom_histogram(colour = "black",
                     lwd = 0.75,
                     linetype = 1,
                     position = "identity",
                     alpha = 0.5) +
      labs(title = paste("Histograma de", varN, "por", varC),
           x = varN, y = "Frecuencia", fill = varC) +
      theme_minimal()
    
    plots[[i]] <- grafico
    i <- i + 1
  }
}

# Mostrar todos en un grid (2 columnas)
grid.arrange(grobs = plots, ncol = 2)
```

### Cat vs Cat
```{r}
for (varc1 in varCat) {
  for (varc2 in varCat) {
    if (varc1 != varc2) {
      prop_table <- prop.table(table(datos[, varc1], datos[, varc2]))
      cat("=============", varc1, " vs. ", varc2, "=========================\n")
      print(prop_table)
    }
  }
}
```
```{r}
par(mfrow = c(3, 3))  
for (varc1 in varCat) {
  for (varc2 in varCat) {
    if (varc1 != varc2) {
      prop_table <- prop.table(table(datos[, varc1], datos[, varc2]))
      barplot(prop_table, beside = TRUE)
    }
  }
}
```

## EDA

```{r}
library(skimr)
library(tidyverse)

## Podem visualitzar un descriptiu de les dades 
skim(datos)
```
```{r}
library(visdat)

## Busquem per a variables numériques o categóriques si hi ha NA's
vis_dat(datos)
## Visualitzem percentatges de NA's en les variables
vis_miss(datos)
```

```{r}
## Generem la matriu de correlacions
datos %>% select(where(is.numeric)) %>% 
  vis_cor()
```

```{r}
library(inspectdf)

## Tipus de dades
inspect_types(datos) %>% show_plot()
```
```{r}
## Comprovem la distribució de les variables 
inspect_num(datos) %>% show_plot()
```

```{r}
## similiar to inspect_imb, but for all levels
inspect_cat(datos) %>% show_plot()
```

```{r}
library(esquisse)
esquisse::esquisser(datos)
```


