---
title: "EDA despues del preprocesado Decision 2"
author: "Grupo 11"
date: "2025-12-13"
output: html_document
---

# Análisis Descriptivo de los datos

## Lectura de los datos

```{r}
#install.packages("dplyr")
library(dplyr)
```


```{r}
datos<-read.csv("datos_decision_2_sin_mahalanobis.csv")
dim(datos)       
head(datos)       
summary(datos)   
```

## Tipos de variables
```{r}
clases <- sapply(datos, class)
datos$HasCrCard <- as.factor(datos$HasCrCard)
datos$IsActiveMember <- as.factor(datos$IsActiveMember)
datos$SavingsAccountFlag <- as.factor(datos$SavingsAccountFlag)

clases <- sapply(datos, class)
varNum <- names(clases)[which(clases %in% c("numeric", "integer"))]
varCat <- names(clases)[which(clases %in% c("character", "factor"))]
```

### Numéricas

```{r}
library(psych)
psych::describe(datos[, varNum])
```

```{r}
par(mfrow = c(2, 4))  
for (var in varNum) {
  hist(datos[, var], main = paste0("Histograma variable ", var))
  boxplot(datos[, var], main = paste0("Boxplot variable ", var))
}

```

### Categóricas
```{r}
for (var in varCat) {
  tablaAbs <- data.frame(table(datos[, var]))
  tablaFreq <- data.frame(table(datos[, var])/sum(table(datos[, var])))
  m <- match(tablaAbs$Var1, tablaFreq$Var1)
  tablaAbs[, "FreqRel"] <- tablaFreq[m, "Freq"]
  colnames(tablaAbs) <- c("Categoria", "FreqAbs", "FreqRel")
  
  cat("===============", var, "===================================\n")
  print(tablaAbs)
  cat("==================================================\n")
}
```
```{r}
par(mfrow = c(2, 3))  
for (var in varCat) {
  barplot(table(datos[, var]))
}
par(mfrow = c(1, 1))  
```

## Análisis exploratorio Bivariante

### Num vs Num
```{r}
cor(datos[, varNum])
```


### Cat vs Cat
```{r}
for (varc1 in varCat) {
  for (varc2 in varCat) {
    if (varc1 != varc2) {
      prop_table <- prop.table(table(datos[, varc1], datos[, varc2]))
      cat("=============", varc1, " vs. ", varc2, "=========================\n")
      print(prop_table)
    }
  }
}
```
```{r}
par(mfrow = c(3, 3))  
for (varc1 in varCat) {
  for (varc2 in varCat) {
    if (varc1 != varc2) {
      prop_table <- prop.table(table(datos[, varc1], datos[, varc2]))
      barplot(prop_table, beside = TRUE)
    }
  }
}
```

## EDA

```{r}
library(skimr)
library(tidyverse)

skim(datos)
```
```{r}
library(visdat)

vis_dat(datos)
vis_miss(datos)
```




```{r}
library(inspectdf)

inspect_types(datos) %>% show_plot()
```
```{r}
inspect_num(datos) %>% show_plot()
```

```{r}
inspect_cat(datos) %>% show_plot()
```

# Selección de variables
```{r}
#install.packages("randomForest")
library(caret)
library(corrplot)
library(randomForest)
library(dplyr)
library(tidyr)

numeric_cols <- sapply(datos, is.numeric)
datos_num <- datos[, numeric_cols]

# Guardamos la variable objetivo y la eliminamos de los numéricos

if ("Exited" %in% names(datos_num)) {
  target <- datos_num$Exited
  datos_num <- datos_num[, names(datos_num) != "Exited", drop = FALSE]
} else {
  target <- datos$Exited
}

# Varianza nula 
nzv <- nearZeroVar(datos_num, saveMetrics = TRUE)
datos_nv <- datos_num[, !nzv$nzv]
cat("Variables eliminadas por baja varianza:", sum(nzv$nzv), "\n")
```

```{r}
# Correlación
cor_matrix <- cor(datos_nv, use = "complete.obs")
high_cor <- findCorrelation(cor_matrix, cutoff = 0.9)
if (length(high_cor) > 0) {
  cat(" Eliminadas por alta correlación:", length(high_cor), "\n")
  datos_corr <- datos_nv[, -high_cor, drop = FALSE]
} else {
  datos_corr <- datos_nv
  cat(" No hay correlaciones altas.\n")
}

library("corrplot")

matriz_corr <- cor(datos_nv[, 1:12])
corrplot(matriz_corr, method = "circle")
```

```{r}
# Combinaciones lineales
datos_corr_na <- drop_na(datos_corr)
combos <- findLinearCombos(datos_corr_na)
if (!is.null(combos$remove)) {
  datos_lineales <- datos_corr_na[, -combos$remove, drop = FALSE]
  cat(" Eliminadas por combinaciones lineales:", length(combos$remove), "\n")
} else {
  datos_lineales <- datos_corr_na
  cat(" No se encontraron combinaciones lineales.\n")
}
```

## Varibles relevantes (predictores vs output)
```{r}
clases <- sapply(datos, class)
varNum <- names(clases)[which(clases %in% c("numeric", "integer"))]
varCat <- names(clases)[which(clases %in% c("character", "factor"))]

# Variables numéricas 
pvals_num <- sapply(varNum, function(v) {
  mod <- lm(datos[[v]] ~ datos$Exited)
  anova(mod)[["Pr(>F)"]][1]
})

# Variables categóricas 
pvals_cat <- sapply(varCat, function(v) {
  if (length(unique(na.omit(datos[[v]]))) > 1) {
    suppressWarnings(chisq.test(table(datos[[v]], datos$Exited))$p.value)
  } else {
    NA  
  }
})

# Combinar y mostrar pvalores
pvals <- c(pvals_num, pvals_cat)
pvals <- sort(pvals)

# Mostrar todas ordenadas por significación
pvals

# Variables que aportan muy poco (p > 0.05)
variables_poco_relevantes <- names(pvals[pvals > 0.05])
variables_poco_relevantes
variables_relevantes <- names(pvals[pvals < 0.05])
variables_relevantes

datos_relevantes <- datos[, c("ID", variables_relevantes)]
write.csv(datos_relevantes, "datos_relevantes_Train_Decision2.csv", row.names = FALSE)
```

